### ISSUE TITLE
spread2 function throws an error if the 'start' input has duplicate start points 

### ISSUE THREAD

**Issue by TylerMuhly** [PredictiveEcology/SpaDES.tools#78]
**Summary of Issue** 
I have a use-case where I'm using the spread2 function to 'spread' dispersing animals across a large landscape. These animals can have duplicate origin points, which causes an error, I suspect when the function binds the spread locations to the origin ID. 

We can resolve this issue by splitting the duplicates into multiple input objects values for the spread2 fxn and then stitching them together afterwards, but I thought you might want to be aware of the issue in case you want to build the ability to handle duplicates into the function.

I'd also like to learn more about the warning message. Our spreadProb is a raster input, and I'm curious if there is an alternate input object type we can and should use?

Thanks for your time! 

**Error and Warning Messages**
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 48 rows; more than 46 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.

In addition: Warning message:
In SpaDES.tools::spread2(pix.raster, start = dispersers$pixelid,  :
  spreadProb is a raster layer stored on disk. This may cause spread2 to be very slow. We suggest extracting the values to a numeric vector first, then passing this to spreadProb

**Code for Reprex**
pix.raster <- raster::raster (paste0 (data.dir, "pix_raster_spread2_reprex.tif"))
spread.raster <- raster::raster (paste0 (data.dir, "spread_raster_spread2_reprex.tif"))
dispersers <- as.data.table (read.csv (paste0 (data.dir, "dispersers_spread2_reprex.csv")))
table.disperse <- SpaDES.tools::spread2 (pix.raster, 
                                             start = dispersers$pixelid, 
                                             spreadProb = spread.raster, 
                                             exactSize = 785000, 
                                             allowOverlap = T, 
                                             asRaster = F, 
                                             circle = F)
_this works:_
dispersers.no.dupes <- dispersers[!duplicated(dispersers$pixelid),]
table.disperse <- SpaDES.tools::spread2 (pix.raster, 
                                             start = dispersers.no.dupes$pixelid, 
                                             spreadProb = spread.raster, 
                                             exactSize = 785000, 
                                             allowOverlap = T, 
                                             asRaster = F, 
                                             circle = F)
**Data for Reprex**
[reprex_data.zip](https://github.com/PredictiveEcology/SpaDES.tools/files/10060713/reprex_data.zip)

**Comment by eliotmcintire** [comment]
Hi @TylerMuhly I'm looking into this. I was able to reproduce the error. Now thinking about it...

In the mean time, just place `[]` at the end of the `spreadProb` raster... see timings below. it is 14x faster!
```
> set.seed(1)
> system.time(try(table.disperse <- SpaDES.tools::spread2 (pix.raster,
+                                          start = dispersers$pixelid,
+                                          spreadProb = spread.raster,
+                                          exactSize = 785000,
+                                          allowOverlap = T,
+                                          asRaster = F,
+                                          circle = F)))
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 9 rows; more than 6 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.
In addition: Warning message:
In SpaDES.tools::spread2(pix.raster, start = dispersers$pixelid,  :
  spreadProb is a raster layer stored on disk. This may cause spread2 to be very slow. We suggest extracting the values to a numeric vector first, then passing this to spreadProb
   user  system elapsed 
 84.006   5.330  70.191 
> set.seed(1)
> system.time(try(table.disperse <- SpaDES.tools::spread2 (pix.raster,
+                                          start = dispersers$pixelid,
+                                          spreadProb = spread.raster[], # <-------- place [] to extract the vector
+                                          exactSize = 785000,
+                                          allowOverlap = T,
+                                          asRaster = F,
+                                          circle = F)))
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 9 rows; more than 6 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.
   user  system elapsed 
 16.615   0.198   5.186 
 ```

**Comment by eliotmcintire** [comment]
> I suspect when the function binds the spread locations to the origin ID.

I believe this is the correct diagnosis...

**Comment by eliotmcintire** [comment]
At the risk of sounding off base, I am not sure if what you want is the `spread2` function as it stands. Perhaps yes, but given the context, it seems like a "no". The `spread2` does a "contagious" process that _increases_ or _decreases_ number of pixels that are associated with an ID (e.g., starting location). For the case of an animal, that seems a bit weird as it means that it is spreading to more than one location and keeps expanding outwards. 

## Options:

1. There is a `crw` function in `SpaDES.tools` that does a correlated random walk, but it doesn't have a notion of `spreadProb`. 

2. I have introduced (in the past hour) a new argument which seems to be working, which probably is not (yet) quite what you need. If you want to try it, I have pushed it to a branch and  you can get it with:

3. I will be working on a step selection-type algorithm in the next few months working with @JWTurn (Julie Turner). Interested in being part of that?

4. See if [NetLogoR](https://github.com/PredictiveEcology/NetLogoR) can help out as it is developed for agent based modeling in mind

## Details

I hesitate to "fix" the error you were getting because it comes about because of the diagnosis you identified, namely more than one "individual" shared the same ID. If you think of this function as a "fire" spreading outwards, it doesn't make much sense to have 3 fires starting in the same pixel because it doesn't burn "more" neighbours if a pixel burns completely because of 3 ignitions or 1 ignition. Furthermore, the error only comes about because there were "zero" pixels that the individual could spread to because `spreadProb` was actually zero in all neighbouring cells. So, that part of the algorithm is actually the "jumping" or "spotting" part where it literally tries to jump over (and not touch) non-neighbouring cells.

## Upshot

So in the end, I am not going to "fix" anything because I don't think it is what is needed here. I have, however, added an error message with a suggestion if you do happen to ask for duplicated `start` locations. Currently, the math/algorithm is incorrect if you pass duplicate `start` locations. 

## Trying 

If you want to try Option 2 above, you can get it with this, noting the new argument `oneNeighbourOnly`
```
remotes::install_github("PredictiveEcology/SpaDES.tools@oneNeighbourOnly")
# 
dispersers.no.dupes <- dispersers[!duplicated(dispersers$pixelid),]
data.table::setDTthreads(1)  # THIS HELPS SPEEDING THINGS UP BY 30% on my system
system.time(table.disperse <- SpaDES.tools::spread2 (pix.raster,
                                                     start = dispersers.no.dupes$pixelid,
                                                     spreadProb = spread.raster[],             # Specify the vector with [ ]
                                                     oneNeighbourOnly = TRUE,                  # THE NEW PART
                                                     iterations = 2000,                        # THIS MAYBE NOT WHAT YOU WANT
                                                     allowOverlap = 2,
                                                     asRaster = F,
                                                     circle = F, plot.it = F))
```
